language: rust

matrix:
  include:
    - rust: nightly
      script:
        - cargo test
        - cargo test --manifest-path ui/Cargo.toml
        - cargo run --example replace
        - cargo run --example comma_separated
    - rust: beta
    - rust: stable
    - rust: 1.31.0

script: cargo test
