language: rust

matrix:
  include:
    - rust: nightly
      script:
        - cargo test
        - cargo run --example replace
        - cargo run --example comma_separated
    - rust: beta
    - rust: stable
    - rust: 1.36.0
    - rust: 1.31.0
      script: cargo check

script: cargo test
