[package]
name = "tt-call"
version = "1.0.5"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Token tree calling convention"
repository = "https://github.com/dtolnay/tt-call"
documentation = "https://docs.rs/tt-call"
readme = "README.md"
edition = "2018"

[dev-dependencies]
rustversion = "0.1"
syn = { version = "0.15", features = ["extra-traits"] }
trybuild = "1.0"

[badges]
travis-ci = { repository = "dtolnay/tt-call" }
