[package]
name = "tt-call"
version = "1.0.2"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Token tree calling convention"
repository = "https://github.com/dtolnay/tt-call"
documentation = "https://docs.rs/tt-call"
readme = "README.md"

[dev-dependencies]
compiletest_rs = "0.3"
syn = { version = "0.14", features = ["extra-traits"] }

[badges]
travis-ci = { repository = "dtolnay/tt-call" }
