[package]
name = "tt-call"
version = "1.0.4"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Token tree calling convention"
repository = "https://github.com/dtolnay/tt-call"
documentation = "https://docs.rs/tt-call"
readme = "README.md"

[dev-dependencies]
syn = { version = "0.15", features = ["extra-traits"] }

[badges]
travis-ci = { repository = "dtolnay/tt-call" }
