[package]
name = "tt-call-tests"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[[bin]]
name = "tt-call-tests"
path = "main.rs"

[dev-dependencies]
compiletest_rs = "0.3"
tt-call = { path = ".." }
